### ISSUE TITLE
I need some help.

### ISSUE THREAD

**Issue by cjhickson647** [vollborn/minecraft-nginx-reverse-proxy#1]
So this is a pretty neat thing you have here. I just went through a lot by trying to set it up. I was able to set it up, but I can't change the ip and port. bash: ./sethost.sh: No such file or directory I just get that error every time I enter the bash command.
![image](https://user-images.githubusercontent.com/77416223/184256657-1c3206d5-5b9b-445c-b210-ce4e0420cfb3.png)
Do you have any idea why this is happening?

**Comment by cjhickson647** [comment]
Ok so I've figured it out. My version of docker makes docker-compose not a command. Instead, it's "docker compose". So I've updated the IP and port. But is there a way to check what it's currently running?

**Comment by cjhickson647** [comment]
Also does it need to be an ip like 192.167.30.20? Or can it be a dns like subdomain.ddns.net?

**Comment by cjhickson647** [comment]
I put my public ip in and it doesn't work.

**Comment by cjhickson647** [comment]
Does this need to use iptables or is firewalld compatible?

**Comment by vollborn** [comment]
Hello there!

First of all, no, it does not need to be an ip address. It can also be a domain name, as long as your proxy server can resolve these, and your DDNS provider is not purely made for HTTP traffic.

Second, you are right. I haven't thought about adding support for docker-ce instead of docker.io users. I should do that.

In your screenshot it seems like you are currently in the src directory. Please cd back in the repositories root directory. There the script should be found.

Please note: in the script I am using the wrong docker-compose syntax for you too. You can execute the command directly instead, it should do the job:

```shell
docker compose exec proxy bash /opt/set_host.sh <ip> <port>
```

Example:
```shell
docker compose exec proxy bash /opt/set_host.sh mineplex.com 25565
```

FYI:
I'm looking forward to adding initial values via environment variables to the container, so these workarounds get obsolete for all kind of users in the future...

**Comment by cjhickson647** [comment]
Yeah I figured a lot of this out, however I can't get it to work properly because I can't open ports properly. I tried using firewalld but it didn't work, I somewhat tried to use iptables, it still didn't work. So I am stuck there at the moment.

**Comment by vollborn** [comment]
I don't know a lot about firewall configurations.

What I did:
I enabled access to port 25565/tcp on my proxy machine, and the same port and protocol on my minecraft server.

Is your minecraft server reachable without using the proxy? By directly connecting to your game servers ip address?

And please note: this container is only capable of forwarding packets for Minecraft: Java Edition. Just in case you are trying to play Minecraft: Bedrock with it, it uses different ports. Another thing I could add.

**Comment by vollborn** [comment]
I am currently facing the same issues while testing with a domain instead of an ip address. It worked a while ago, for sure.
The container itself can resolve the host, but nginx does not, for some reason.

**Comment by cjhickson647** [comment]
Alright, well I don't know how to open ports properly, and I am using a Java server with geyser installed. However it should be able to ping the domain. If you can tell me how you opened your ports maybe I can go from there.

**Comment by cjhickson647** [comment]
But it would be very nice if you updated your project to include geyser support.

**Comment by vollborn** [comment]
On my servers I am using Ubuntu with its preinstalled firewall ufw.
To enable access, you can run:

```shell
ufw allow 25565/tcp
```

And to enable the firewall:
```shell
ufw enable
```

I am not familiar with firewalld or iptables directly. I am used to the simplicity of ufw 🤓 
You can also try to disable all your firewalls first, just for testing purposes. Then you can see, if that is really the issue... nothing should be blocked then.

**Comment by cjhickson647** [comment]
So basically, Oracle Linux 8 is screwing me over. I should have realized after it took so much to set everything up.

**Comment by cjhickson647** [comment]
Alright, I scrapped my Oracle Linux 8 instance and got Ubuntu. I downloaded docker.io and docker-compose. I git cloned the repo, copied the .env file, built the container, started the container, set the ip, yet it still says the port isn't open. I even disabled ufw.
![image](https://user-images.githubusercontent.com/77416223/184453732-f0b59e7d-a6d0-4c66-b144-8d09c3ac69c5.png)
![image](https://user-images.githubusercontent.com/77416223/184453737-b4a775c7-dcaa-47c1-918a-ab1b3a6b0780.png)

**Comment by cjhickson647** [comment]
The interesting thing is that is says 25565 but not 22 which is open so I can ssh.
![image](https://user-images.githubusercontent.com/77416223/184454476-deaf40bb-320f-4148-a243-fbd45ca611df.png)

**Comment by vollborn** [comment]
Do not leave your current ssh session, until you've added 22/tcp to your firewall. You may lose access to your server otherwise...

**Comment by cjhickson647** [comment]
bruh ive left my ssh connection like 3 times
something else is controlling my ports and idfk what is

**Comment by vollborn** [comment]
Okay... what? This is a clean install? Like... issues like this never happened to me before.
Maybe it is a thing of your provider? Or are you self-hosting?

**Comment by cjhickson647** [comment]
Yes it is a clean install. My provider is the Oracle Cloud Infrastructure. It has a network going with 25565 open. Yet the ports are still closed.

**Comment by cjhickson647** [comment]
I'm going to jump off a cliff.
![image](https://user-images.githubusercontent.com/77416223/184455438-e7cb9e35-3ed4-4c40-8fcb-3146a8ca4d11.png)

**Comment by vollborn** [comment]
Wow. That's why I never encountered such problems 😂

**Comment by vollborn** [comment]
I am going to close this issue, as it does not really affect this repository, more your provider / server setup.

Feel free to add me on Discord (Basic#7612), if you got anymore questions regarding your case 👍🏻

**Comment by cjhickson647** [comment]
Yep. Will do.
